### ISSUE TITLE
Uneven allocation of consumers to shards despite sufficient pause

### ISSUE THREAD

**Issue by kishorenc** [rabbitmq/rabbitmq-sharding#24]
We've 24 consumers (one consumer in each physical machine) which listens to a sharded queue. We're witnessing an issue of the consumers being unevenly distributed across the 3 queues. For e.g. we often see a 10+10+4 distribution. 

Our consumers are restarted with atleast a 1 minute interval between the restarts. I read in the documentation that a race condition could potentially occur when the restarts happen all-at-once, but here, that is definitely not the case. 

Furthermore, when we tried adding an additional machine (and hence an additional consumer), it does not get assigned to the queue with 4 consumers but joined one of the queues with 10 consumers. 

I suspect a bug here, and would appreciate any pointers on what could be going wrong.

**Comment by michaelklishin** [comment]
How can we reproduce?

**Comment by kishorenc** [comment]
This turned out to be a problem with the way we had implemented our solution. Sorry for the false alarm!

**Comment by jamescarr** [comment]
@michaelklishin for some context, haproxy routed consumers to any box on our rabbitMQ cluster. This wound up meaning that could land on any box and since the workers are a subset of consumers there was no guarantee on whether or not these specific consumers were well balanced. 

It seems the logic in `least_consumers` only routes to queues that are present on the actual node vs. the entire cluster.

**Comment by volak** [comment]
That's an interesting find!  I was just looking into why my consumers were being unevenly allocated to sharded queues.
Since HaProxy is the recommended way to connect to a rabbitmq cluster maybe this fact should be mentioned in the docs or someplace?  I'm going to do some testing with haproxy `balance leastconn` to see if that helps.. used to be `roundrobin`

**Comment by michaelklishin** [comment]
HAproxy is a way to connect to a RabbitMQ cluster. We can mention it in the docs for this plugin.

**Comment by volak** [comment]
@kishorenc Yes it did - it wasnt perfect balance but significantly better

**Comment by julienbonastre** [comment]
Yep, well I already had mine on `leastconn` but this still presented the behaviour of badly distributed consumer/queue ratios even with just a 2 node cluster 😢 

I will have to revert my original worker code which was using a redis queue locking regime with an auto-expiring (TTL) key logic to determine which node/queue and shard was available or not yet being consumed from and spinning up the amqp consumer accordingly on a available one.. pretty clunky but at least it provided some more deterministic balancing .....

Anywho
