### ISSUE TITLE
RabbitMQ Sharding behind a load balancer

### ISSUE THREAD

**Issue by gwjames** [rabbitmq/rabbitmq-sharding#27]
I have a setup as follows:

5 node cluster, running X shards per node (currently 3). I am only wanting to run 1 exchange. This means that I need to run 15 consumers but they key is to run 3 consumers explicitly on each of the 5 nodes. In front of the cluster is an AWS ELB. The problem here is that if I simply startup 5 connections, each loading up 3 consumers, it isn't guaranteed that each of the 5 connections will go to a unique node. I might end up with 3 of the connections going to a unique server and 2 of the connections going to the same server, leaving 3 queues not being consumed from.

What is the recommended approach here? I can't explicitly make a connection to each node since this doesn't really effectively allow for auto-scaling.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
