### ISSUE TITLE
Auto-deletion of queues

### ISSUE THREAD

**Issue by gwjames** [rabbitmq/rabbitmq-sharding#28]
With normal RabbitMQ queues/exchanges, I set the autodelete and x-expiry settings to ensure that when all consumers have died, everything gets cleaned up and deleted.

I've noticed that with RabbitMQ-sharding, the queues get created with no settings since my app doesn't explicitly create the queues. Is there some way to pass along settings such as the auto-delete to the created queues?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
