### ISSUE TITLE
Channels are not distribuited over all shards

### ISSUE THREAD

**Issue by mvleandro** [rabbitmq/rabbitmq-sharding#29]
I configured the exchange to have 8 shards per node.

When my consumers comes up, they are not distribuited over all shards, and some shards stay without consumers.

I added a delay after each channel creation, but even after that the problem persists.

I think it may be a bug. Could anyone help me?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The docs contain [a dedicate section](https://github.com/rabbitmq/rabbitmq-sharding#load-distribution-and-consumer-balancing) on some important factors that can affect this plugin. Connection and channel distribution is not controlled by this plugin in any way.

We cannot suggest anything without a code example that can be used to reproduce and reasonably detailed data from the node. This is mailing list material.
