### ISSUE TITLE
Does anyone know how to use sharding in celery?

### ISSUE THREAD

**Issue by xcTorres** [rabbitmq/rabbitmq-sharding#38]
I don't know how to set the route.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
You need to

 * Declare an exchange of a certain type recommended in the README
 * Set up a sharding policy
 * Make Celery use said exchange and consume from a sharded queue (again, see the README)

If Celery or similar projects do not support arbitrary exchanges of custom types, or do not allow queue names to be overridden for consumers, they cannot realistically support this plugin, although [exchange-to-exchange bindings](https://www.rabbitmq.com/e2e.html) can be potentially used for a workaround.
